#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt NO_HUP

export EDITOR="emacs"

# Case insensitive globbing
setopt NO_CASE_GLOB

# Globs
setopt NUMERIC_GLOB_SORT
setopt EXTENDED_GLOB
